# Generated by Django 3.0.3 on 2020-03-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0002_auto_20200310_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
