# Generated by Django 3.0.4 on 2020-05-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0003_quiz_quiz_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_name',
        ),
    ]
