# Generated by Django 3.0.4 on 2020-05-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0004_auto_20200505_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200, null=True)),
                ('resource_location', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
